### ISSUE TITLE
租户列表-查询参数

### ISSUE THREAD

**Issue by OweQian** [IoTSharp/ClientAppWithVue#3]
/api/Tenants
params确认：pi和ps字段的含义
![image](https://user-images.githubusercontent.com/25632596/194000651-b018c8d7-32ee-48af-b36e-16f17cd31ea2.png)

**Comment by maikebing** [comment]
王强:
不管那个参数

王强:
那个是表格里带出来的

麦壳饼:
哦。 

王强:
一直没有删
